name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
        image: node:20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Get SSH Key and set permission
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./dist/mygifts-test/browser ubuntu@52.28.37.136:/var/www/mygifts-test
