# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Testing scp'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Get SSH credentials
      run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-created-on-lightsail
            chmod 600 ~/.ssh/github-actions-created-on-lightsail
    - name: Deploy using SCP
      run: scp -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-created-on-lightsail ./dist/mygifts-test/browser/* ubuntu@52.28.37.136:/var/www/mygifts-test
